[2025-09-16T03:30:29.488+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_saved_tracks_etl_pipeline.gold_saved_transform manual__2025-09-16T03:19:11.428253+00:00 [queued]>
[2025-09-16T03:30:29.497+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_saved_tracks_etl_pipeline.gold_saved_transform manual__2025-09-16T03:19:11.428253+00:00 [queued]>
[2025-09-16T03:30:29.497+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-09-16T03:30:29.708+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): gold_saved_transform> on 2025-09-16 03:19:11.428253+00:00
[2025-09-16T03:30:29.722+0000] {standard_task_runner.py:57} INFO - Started process 30238 to run task
[2025-09-16T03:30:29.726+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spotify_saved_tracks_etl_pipeline', 'gold_saved_transform', 'manual__2025-09-16T03:19:11.428253+00:00', '--job-id', '979', '--raw', '--subdir', 'DAGS_FOLDER/spotify_saved_dag.py', '--cfg-path', '/tmp/tmptysy2nhv']
[2025-09-16T03:30:29.729+0000] {standard_task_runner.py:85} INFO - Job 979: Subtask gold_saved_transform
[2025-09-16T03:30:29.787+0000] {task_command.py:415} INFO - Running <TaskInstance: spotify_saved_tracks_etl_pipeline.gold_saved_transform manual__2025-09-16T03:19:11.428253+00:00 [running]> on host 537418afed42
[2025-09-16T03:30:29.847+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_saved_tracks_etl_pipeline' AIRFLOW_CTX_TASK_ID='gold_saved_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T03:19:11.428253+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T03:19:11.428253+00:00'
[2025-09-16T03:30:29.880+0000] {logging_mixin.py:151} INFO - Executed sql/gold/saved_tracks/fact_saved_songs.sql
[2025-09-16T03:30:29.896+0000] {logging_mixin.py:151} INFO - Executed sql/gold/saved_tracks/dim_saved_tracks.sql
[2025-09-16T03:30:29.904+0000] {logging_mixin.py:151} INFO - Executed sql/gold/saved_tracks/dim_saved_artists.sql
[2025-09-16T03:30:29.910+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/etl/db_utils.py", line 11, in run_sql_scripts
    cur.execute(sql)
psycopg2.errors.UndefinedTable: relation "gold_dim_saved_albums" does not exist

[2025-09-16T03:30:29.921+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_saved_tracks_etl_pipeline, task_id=gold_saved_transform, execution_date=20250916T031911, start_date=20250916T033029, end_date=20250916T033029
[2025-09-16T03:30:29.946+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 979 for task gold_saved_transform (relation "gold_dim_saved_albums" does not exist
; 30238)
[2025-09-16T03:30:29.994+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-16T03:30:30.047+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
