[2025-09-29T05:16:15.758+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_etl_pipeline.extract_genres scheduled__2025-09-29T02:00:00+00:00 [queued]>
[2025-09-29T05:16:15.766+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_etl_pipeline.extract_genres scheduled__2025-09-29T02:00:00+00:00 [queued]>
[2025-09-29T05:16:15.767+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-09-29T05:16:15.777+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_genres> on 2025-09-29 02:00:00+00:00
[2025-09-29T05:16:15.788+0000] {standard_task_runner.py:57} INFO - Started process 93033 to run task
[2025-09-29T05:16:15.795+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spotify_etl_pipeline', 'extract_genres', 'scheduled__2025-09-29T02:00:00+00:00', '--job-id', '2761', '--raw', '--subdir', 'DAGS_FOLDER/spotify_dag.py', '--cfg-path', '/tmp/tmp2r7qydqq']
[2025-09-29T05:16:15.800+0000] {standard_task_runner.py:85} INFO - Job 2761: Subtask extract_genres
[2025-09-29T05:16:16.443+0000] {task_command.py:415} INFO - Running <TaskInstance: spotify_etl_pipeline.extract_genres scheduled__2025-09-29T02:00:00+00:00 [running]> on host 8522660cfb6a
[2025-09-29T05:16:16.561+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_genres' AIRFLOW_CTX_EXECUTION_DATE='2025-09-29T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-29T02:00:00+00:00'
[2025-09-29T05:16:20.779+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_dag.py", line 52, in extract_genres_task
    fetch_artist_genres(df["artist_id"].tolist())
  File "/opt/airflow/etl/extract.py", line 96, in fetch_artist_genres
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.spotify.com/v1/artists/6KImCVD70vtIoJWnq6nGn3
[2025-09-29T05:16:20.805+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_etl_pipeline, task_id=extract_genres, execution_date=20250929T020000, start_date=20250929T051615, end_date=20250929T051620
[2025-09-29T05:16:20.856+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2761 for task extract_genres (429 Client Error: Too Many Requests for url: https://api.spotify.com/v1/artists/6KImCVD70vtIoJWnq6nGn3; 93033)
[2025-09-29T05:16:20.887+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-29T05:16:21.403+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
